### ISSUE TITLE
Contactar a Vinicius Senger (https://twitter.com/vsenger) para el tema de los juegos para enseñar Java

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/java-dominicano-comite-ejecutivo#13]

**Comment by ecabrerar** [comment]
@xTryHard y @BrayanMnz hay que darle seguimiento a la conversación que iniciaron con Vinicius Senger.

**Comment by BrayanMnz** [comment]
Vinicius no admite DM de personas que no sigue y no veo su correo.

**Comment by xTryHard** [comment]
Encontré este en su GitHub: mailto:vsenger@amazon.com

**Comment by ecabrerar** [comment]
@xTryHard llegaste a escribirle a vinicius?
