### ISSUE TITLE
Pago renovación servicio de correo

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/java-dominicano-comite-ejecutivo#16]
Adjunto el comprobante de pago de la renovación del servicio de correo
[Proton Mail invoice 15681957.pdf](https://github.com/JavaDominicano/java-dominicano-comite-ejecutivo/files/11426902/Proton.Mail.invoice.15681957.pdf)
El monto en peso corresponde a 3,022.42.

**Comment by BrayanMnz** [comment]
El pago se ha liquidado de los fondos de la comunidad, 
comprobante enviado por correo. 

Hoja de cálculo con ingresos y egresos de la comunidad actualizada.
https://docs.google.com/spreadsheets/d/1FuPPgFh0C6gjkH16AXz2LDffjzM0egiGzFgvAMbMaXM/edit#gid=527874789
