### ISSUE TITLE
Dar seguimiento al registro de la comunidad como entidad sin fines de lucros

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/java-dominicano-comite-ejecutivo#2]
He tratado de comunicarme varias veces con Joan Jimenez y no responde los mensajes, estoy a la espera de que confirme si la información que nosotros le enviamos está completa o require otras informaciones.

Así como también, necesitamos tener un estimado del tiempo en que tendriamos el registro.

**Comment by ecabrerar** [comment]
@vacax recuerda darle seguimiento a este caso.

**Comment by vacax** [comment]
Dando seguimiento a Joan.

**Comment by ecabrerar** [comment]
Proceso finalizado
