### ISSUE TITLE
Agregar información de la reunión del día 9 de Enero de 2024

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/java-dominicano-comite-ejecutivo#27]
Buenas noches @fredpena cuando tengas tiempo, favor agregar las informaciones de la reunión aquí.

**Comment by fredpena** [comment]
Minuta 9 de Enero 2024

- Dos reuniones mensuales para el JUG, martes a las 7 PM.
- Para el JConf, planificar reuniones cada 15 días.
- Analizar los tickets a ciegas.
- Máximo en febrero definir el precio de las boletas.
- Empezar a vender a inicio de marzo.
- El paquete de patrocinio debe estar listo en las próximas dos semanas.
- Publicar todas las semanas una infografía (crear plan de trabajo).
- Crear un plan de trabajo para hacer engagement con los usuarios que están en las distintas plataformas.
- Eliezer va a crear tips de recomendaciones para trabajar las infografías.
- Seguir uniéndose a las distintas llamadas (JCP, MicroProfile).
- Tratar de registrar el JUG en el JCP.
- Camacho se va a registrar en el JCP.
- Hacer un HackDay para terminar la página del JUG.
- Sumarnos a la iniciativa Hacker Garten.
- Preparar un taller con Apache NiFi.
- Se programarán las reuniones por el año entero.
- Revisar documentos de Carlos Obregón para colaborar con él y ver la posibilidad de poder escalarlo a Java In Education.
- Revisar la propuesta de Carlos Obregón y Eugenio, Freddy para ver si la podemos unificar.
- Hacer esquema de patrocinio (membresia) para que empresas y personas se motiven a aportar
- Actualizar el MontlysTalks para organizar los eventos del 2024
- Actualizar la portada del MontlysTalks

**Comment by ecabrerar** [comment]
Disculpa @fredpena, no especifiqué más arriba, chequea el readme y el formato que teníamos para las reuniones.

**Comment by fredpena** [comment]
> Disculpa @fredpena, no especifiqué más arriba, chequea el readme y el formato que teníamos para las reuniones.

Listo. Hay PR para la actualización

**Comment by ecabrerar** [comment]
Gracias @fredpena
