### ISSUE TITLE
Crear una guía general para las publicaciones de infografía

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/java-dominicano-comite-ejecutivo#28]
Escribir una guía general con los lineamientos que se deben seguir al escribir una infografía.

Ver esta guía : https://docs.google.com/document/d/1v7i2qJql59zffgGQVa1WecPrYAk0FHuepH-nhzREZMI/edit?usp=sharing

Escribir la guía en este documento https://docs.google.com/document/d/1_FPhnp2Is-3B8dDg15onB4iksluKjfrtm1teAn5ozdM/edit?usp=sharing

**Comment by zerh** [comment]
En progreso

**Comment by zerh** [comment]
En progreso

**Comment by zerh** [comment]
Listo, lo dejo para revisión.

**Comment by ecabrerar** [comment]
Hice algunas correcciones ortográficas en el documento de google doc.
@zerh vas a incluir algunas recomendaciones si deseamos agregar imágenes a la infografía?
