### ISSUE TITLE
Seguimiento a conversaciones sostenidas en Devnexus 2023

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/java-dominicano-comite-ejecutivo#3]
- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [x] #9
- [ ] #10
- [ ] #11
- [ ] Dar seguimiento a conversación con Foojay (Canal de Slack, Participación en el Podcast)
- [x] #12
- [ ] #13
- [x] #14

**Comment by ecabrerar** [comment]
@BrayanMnz @xTryHard estan todos los temas o falta alguno?

**Comment by xTryHard** [comment]
Se ve bien. Cualquiera cosa, agregaré un comment.

**Comment by BrayanMnz** [comment]
Faltó Foojay, hablar con ellos y promocionar con ellos el evento. 
Entiendo que sería bueno confirmar algunos speakers primero antes de solicitarles participar en el podcast.
