### ISSUE TITLE
Escribirle a Francisco Contreras para un contacto con Digital Ocean

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/java-dominicano-comite-ejecutivo#37]

**Comment by ecabrerar** [comment]
Contacté a francisco y me pasó estas informaciones:
For Event / Hackathon sponsorships, please submit your request through the form   here (https://goo.gl/forms/o3lArqe60vfnly3A2)

**Comment by ecabrerar** [comment]
Pero parece que ya no están recibiendo más solicitudes.

@BrayanMnz favor enviarle un correo a Digital Ocean a esta dirección [sponsorships@digitalocean.com](mailto:sponsorships@digitalocean.com)

**Comment by BrayanMnz** [comment]
Correo enviado.
