### ISSUE TITLE
Pedir confirmación a Teresa su participación

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/java-dominicano-comite-ejecutivo#41]

**Comment by BrayanMnz** [comment]
ETA solicitado vía papercall

**Comment by BrayanMnz** [comment]
Theresa responde que aún está bajo consideración por parte de su empresa, 
dice que hablará con sus superiores y nos dejará saber.

**Comment by ecabrerar** [comment]
Declinó participar
