### ISSUE TITLE
Responder correo enviado por Sonatype sobre su interés de realizar una actividad en el JUG

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/java-dominicano-comite-ejecutivo#5]

**Comment by ecabrerar** [comment]
@BrayanMnz si no ha respondido, favor darle seguimiento y copia a @vacax @BrayanMnz y a mi.

**Comment by BrayanMnz** [comment]
> @BrayanMnz si no ha respondido, favor darle seguimiento y copia a @vacax @BrayanMnz y a mi.

Los incluyo en el loop en la próxima respuesta, ya había respondido el correo inicial.
