### ISSUE TITLE
Enviar correo de seguimiento a Felipe Gutierrez y presentar a Carlos Camacho

### ISSUE THREAD

**Issue by ecabrerar** [JavaDominicano/java-dominicano-comite-ejecutivo#6]

**Comment by vacax** [comment]
Freddy Peña envió el correo presentándome, estamos esperando que responda el mismo.

**Comment by ecabrerar** [comment]
@fredpena camacho me dijo que tu lo había presentado con Felipe. Es necesario enviarle el correo sobre el call for paper para JConf Dominicana o tu correo decía eso ?

**Comment by fredpena** [comment]
> 

@ecabrerar el correo mio es para ver la parte de colabaracion de Spring con la universidad, es buneo que le mande el call for paper.

**Comment by ecabrerar** [comment]
![Screenshot 2023-04-18 at 23-35-21 Dominican Republic JUG and JConf Dominicana 2023 CFP - eudris@gmail com - Gmail](https://user-images.githubusercontent.com/2789130/232960696-1ddefa32-4e29-405a-8a13-6b03823a2adf.png)
